<a href="https://colab.research.google.com/github/PKpacheco/la-2-project/blob/main/Paola_Katherine_LAproject2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px

In [3]:
csv_file_drive = "/content/drive/MyDrive/rrc/algebra/excel_la2.csv"
csv_data = pd.read_csv(csv_file_drive, encoding = "utf-8")
csv_data

condition    voltage      current  temperature
0    normal  13.036111   458.460370     6.879090
1    normal  11.135509   458.156781     6.394905
2    normal  10.296578   459.431151     2.736525
3    normal  10.553064   457.141002     5.624983
4    normal   9.880487   460.601899     1.843793
5    failed  27.614720  4610.433851    56.440862
6    failed  28.455265  4597.874476    55.236113
7    failed  33.977884  4591.018036    48.824006
8    failed  24.817434  4615.117584    46.895674
9    failed  23.380610  4592.524455    52.920179

In [4]:
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   condition    10 non-null     object 
 1   voltage      10 non-null     float64
 2   current      10 non-null     float64
 3   temperature  10 non-null     float64
dtypes: float64(3), object(1)
memory usage: 448.0+ bytes


#Question 1 - a)Calculate the mean 

In [110]:
mean_voltage = csv_data['voltage'].mean().round(2)
mean_current = csv_data['current'].mean().round(2)
mean_temperature = csv_data['temperature'].mean().round(2)

print('>>> mean_voltage = ', mean_voltage)
print('>>> mean_current = ', mean_current)
print('>>> mean_temperature =',mean_temperature)

>>> mean_voltage =  19.31
>>> mean_current =  2530.08
>>> mean_temperature = 28.38


# Question 1 - b)Calculate the std dev

In [112]:
std_voltage = csv_data['voltage'].std().round(2)
std_current = csv_data['current'].std().round(2)
std_temperature = csv_data['temperature'].std().round(2)

print('>>> std_voltage =', std_voltage)
print('>>> std_current =', std_current)
print('>>> std_temperature =',std_temperature)

>>> std_voltage = 9.24
>>> std_current = 2183.37
>>> std_temperature = 25.16


#Question 2 - a)standardized voltage

In [8]:
csv_data['standardized_voltage'] = ((csv_data['voltage'] - mean_voltage )/ std_voltage).round(2)
csv_data.head()

condition    voltage     current  temperature  standardized_voltage
0    normal  13.036111  458.460370     6.879090                 -0.68
1    normal  11.135509  458.156781     6.394905                 -0.88
2    normal  10.296578  459.431151     2.736525                 -0.98
3    normal  10.553064  457.141002     5.624983                 -0.95
4    normal   9.880487  460.601899     1.843793                 -1.02

#Question 2 - b)standardized current

In [9]:
csv_data['standardized_current'] = ((csv_data['current'] - mean_current )/ std_current).round(2)
csv_data.head()

condition    voltage     current  temperature  standardized_voltage  \
0    normal  13.036111  458.460370     6.879090                 -0.68   
1    normal  11.135509  458.156781     6.394905                 -0.88   
2    normal  10.296578  459.431151     2.736525                 -0.98   
3    normal  10.553064  457.141002     5.624983                 -0.95   
4    normal   9.880487  460.601899     1.843793                 -1.02   

   standardized_current  
0                 -0.95  
1                 -0.95  
2                 -0.95  
3                 -0.95  
4                 -0.95

#Question 2 - c)standardized temperature

In [10]:
csv_data['standardized_temperature'] = ((csv_data['temperature'] - mean_temperature )/ std_temperature).round(2)
csv_data.head()

condition    voltage     current  temperature  standardized_voltage  \
0    normal  13.036111  458.460370     6.879090                 -0.68   
1    normal  11.135509  458.156781     6.394905                 -0.88   
2    normal  10.296578  459.431151     2.736525                 -0.98   
3    normal  10.553064  457.141002     5.624983                 -0.95   
4    normal   9.880487  460.601899     1.843793                 -1.02   

   standardized_current  standardized_temperature  
0                 -0.95                     -0.85  
1                 -0.95                     -0.87  
2                 -0.95                     -1.02  
3                 -0.95                     -0.90  
4                 -0.95                     -1.05

#Question 4

In [11]:
from math import sqrt
# define student number 
a = 6
b = 4
c = 4
d = 4

w1_1stpart = 1/(sqrt((19+c-a)**2 + (a)**2 + (43 + d - b)**2))

matrix1 = [(a-c-19), (a*(-1)**b), (b-d-43)]
matrix1


w1 = np.dot(w1_1stpart,matrix1)
w1.round(decimals=2)

bias = 1 / sqrt(2210+a**2)
b1 = round(bias,2)


print('w1', w1,
      'bias', bias)

w1 [-0.36460209  0.12868309 -0.92222881] bias 0.021100615513931942


# Question 4 - b) Calculate lenght vector |w1|

In [12]:
# lenght vector |w1|

# mag = np.sqrt(w1.dot(w1))
# mag

lenght_vector_w1 = np.linalg.norm(w1)
lenght_vector_w1



1.0

# Question 4- c) calculate result of v*w + B

In [13]:
csv_data.head()

condition    voltage     current  temperature  standardized_voltage  \
0    normal  13.036111  458.460370     6.879090                 -0.68   
1    normal  11.135509  458.156781     6.394905                 -0.88   
2    normal  10.296578  459.431151     2.736525                 -0.98   
3    normal  10.553064  457.141002     5.624983                 -0.95   
4    normal   9.880487  460.601899     1.843793                 -1.02   

   standardized_current  standardized_temperature  
0                 -0.95                     -0.85  
1                 -0.95                     -0.87  
2                 -0.95                     -1.02  
3                 -0.95                     -0.90  
4                 -0.95                     -1.05

In [14]:
#define n vectors
n1 = [(csv_data['standardized_voltage'][0]),
      (csv_data['standardized_current'][0]),
      (csv_data['standardized_temperature'][0])]

n2= [(csv_data['standardized_voltage'][1]),
      (csv_data['standardized_current'][1]),
      (csv_data['standardized_temperature'][1])]

n3= [(csv_data['standardized_voltage'][2]),
      (csv_data['standardized_current'][2]),
      (csv_data['standardized_temperature'][2])]
  
n4 = [(csv_data['standardized_voltage'][3]),
      (csv_data['standardized_current'][3]),
      (csv_data['standardized_temperature'][3])]

n5 = [(csv_data['standardized_voltage'][4]),
      (csv_data['standardized_current'][4]),
      (csv_data['standardized_temperature'][4])]

print(n1)
print(n2)
print(n3)
print(n4)
print(n5)

[-0.68, -0.95, -0.85]
[-0.88, -0.95, -0.87]
[-0.98, -0.95, -1.02]
[-0.95, -0.95, -0.9]
[-1.02, -0.95, -1.05]


In [15]:
#define f vectors
f1 = [(csv_data['standardized_voltage'][5]),
      (csv_data['standardized_current'][5]),
      (csv_data['standardized_temperature'][5])]

f2= [(csv_data['standardized_voltage'][6]),
      (csv_data['standardized_current'][6]),
      (csv_data['standardized_temperature'][6])]

f3= [(csv_data['standardized_voltage'][7]),
      (csv_data['standardized_current'][7]),
      (csv_data['standardized_temperature'][7])]
  
f4 = [(csv_data['standardized_voltage'][8]),
      (csv_data['standardized_current'][8]),
      (csv_data['standardized_temperature'][8])]

f5 = [(csv_data['standardized_voltage'][9]),
      (csv_data['standardized_current'][9]),
      (csv_data['standardized_temperature'][9])]

print(f1)
print(f2)
print(f3)
print(f4)
print(f5)

[0.9, 0.95, 1.12]
[0.99, 0.95, 1.07]
[1.59, 0.94, 0.81]
[0.6, 0.95, 0.74]
[0.44, 0.94, 0.98]


In [16]:
compute_n1 = (np.dot(n1, w1)+ b1).round(decimals=2)

compute_n2 = (np.dot(n2, w1)+ b1).round(decimals=2)

compute_n3 = (np.dot(n3, w1)+ b1).round(decimals=2)

compute_n4 = (np.dot(n4, w1)+ b1).round(decimals=2)

compute_n5 = (np.dot(n5, w1)+ b1).round(decimals=2)

compute_f1 = (np.dot(f1, w1)+ b1).round(decimals=2)

compute_f2 = (np.dot(f2, w1)+ b1).round(decimals=2)

compute_f3 = (np.dot(f3, w1)+ b1).round(decimals=2)

compute_f4 = (np.dot(f4, w1)+ b1).round(decimals=2)

compute_f5 = (np.dot(f5, w1)+ b1).round(decimals=2)

print('calculation for n1', compute_n1)
print('calculation for n2', compute_n2)
print('calculation for n3', compute_n3)
print('calculation for n4', compute_n4)
print('calculation for n5', compute_n5)


print('calculation for f1', compute_f1)
print('calculation for f2', compute_f2)
print('calculation for f3', compute_f3)
print('calculation for f4', compute_f4)
print('calculation for f5', compute_f5)



calculation for n1 0.93
calculation for n2 1.02
calculation for n3 1.2
calculation for n4 1.07
calculation for n5 1.24
calculation for f1 -1.22
calculation for f2 -1.21
calculation for f3 -1.19
calculation for f4 -0.76
calculation for f5 -0.92


# Question 4- d) Calculate Loss Function 


In [8]:
L = 10
print ('>>> Loss Function = ', L)
# all values are incorrect

>>> Loss Function =  10


#Question 4 -e) caculate accuracy

In [7]:
A = (10-L)/10
print ('>>> Accuracy = ', A)

>>> Accuracy =  0.0


#Question 5 

In [117]:
# linear mappingover matrix by identity vectors

Me1 = np.array([(-1),(a*10**(-2)),(0)])
Me2 = np.array([(b*10**(-2)),(1),(c*10**(-2))])
Me3 = np.array([(0),(d*10**(-2)),(-1)])

print('me1 =', Me1)
print('me2 =', Me2)
print('me3 =', Me3)
print('----------------------')

print('')

matrix = np.array([[Me1], [Me2], [Me3]])

#transpose to get the vertical values
M= np.array([[Me1], [Me2], [Me3]]).T

print(matrix)
print('----------------------')

print('We have the arrays, horizonal, so we need Transpose for get the values in the vertical way')

print('>>> M =')

print(M)
# w = np.array([1,2,3])
# print('>>> w =', w)
# print('')

# print('>>> matrix result')
# print(matrix)
# print('')

# print('>>> M, result of matmu1 product ')
# print('')

# M = np.matmul(matrix, w)
# print(M)
# print('')

# print('>>> M, result of dot product ')
# M_using_dot = np.dot(matrix,w)
# print(M_using_dot)


me1 = [-1.    0.06  0.  ]
me2 = [0.04 1.   0.04]
me3 = [ 0.    0.04 -1.  ]
----------------------

[[[-1.    0.06  0.  ]]

 [[ 0.04  1.    0.04]]

 [[ 0.    0.04 -1.  ]]]
----------------------
We have the arrays, horizonal, so we need Transpose for get the values in the vertical way
>>> M =
[[[-1.    0.04  0.  ]]

 [[ 0.06  1.    0.04]]

 [[ 0.    0.04 -1.  ]]]


# Question 6- a) find u

In [88]:
#u = Mw1

u = np.dot(M,w1).round(decimals=2)
print(u)

[[0.37]
 [0.07]
 [0.93]]


# Question 6 - b) calculate w2

In [100]:
# w2 = u / |u| 

#calculate the lenght vector

lenght_vector_u =(np.linalg.norm(u)).round(decimals=2)
print('>>> lenght_vector_u = ', lenght_vector_u)


w2= (u / lenght_vector_u).round(decimals=2)
print ('>>> w2 = ')
print (w2)
print('')

b2_calculate = b1 - ((a+1)/10)
b2 = round(b2_calculate,2)

print ('>>> b2 = ', b2)


>>> lenght_vector_u =  1.0
>>> w2 = 
[[0.37]
 [0.07]
 [0.93]]

>>> b2 =  -0.68


# Question 6-c) calculate the v*w+b

In [102]:
compute_n1_b2 = (np.dot(n1, w2)+ b2).round(decimals=2)

compute_n2_b2 = (np.dot(n2, w2)+ b2).round(decimals=2)

compute_n3_b2 = (np.dot(n3, w2)+ b2).round(decimals=2)

compute_n4_b2 = (np.dot(n4, w2)+ b2).round(decimals=2)

compute_n5_b2 = (np.dot(n5, w2)+ b2).round(decimals=2)

compute_f1_b2 = (np.dot(f1, w2)+ b2).round(decimals=2)

compute_f2_b2 = (np.dot(f2, w2)+ b2).round(decimals=2)

compute_f3_b2 = (np.dot(f3, w2)+ b2).round(decimals=2)

compute_f4_b2 = (np.dot(f4, w2)+ b2).round(decimals=2)

compute_f5_b2 = (np.dot(f5, w2)+ b2).round(decimals=2)

print('calculation for n1', compute_n1_b2)
print('calculation for n2', compute_n2_b2)
print('calculation for n3', compute_n3_b2)
print('calculation for n4', compute_n4_b2)
print('calculation for n5', compute_n5_b2)


print('calculation for f1', compute_f1_b2)
print('calculation for f2', compute_f2_b2)
print('calculation for f3', compute_f3_b2)
print('calculation for f4', compute_f4_b2)
print('calculation for f5', compute_f5_b2)

calculation for n1 [-1.79]
calculation for n2 [-1.88]
calculation for n3 [-2.06]
calculation for n4 [-1.94]
calculation for n5 [-2.1]
calculation for f1 [0.76]
calculation for f2 [0.75]
calculation for f3 [0.73]
calculation for f4 [0.3]
calculation for f5 [0.46]


#Question 6 - d) calculate Loss function 

In [12]:
L_for_b2 = 0

print('>>> Loss Function =', L)
#all values are correct

>>> Loss Function = 10


# Question 6 - e) Calaulate Accuracy

In [13]:
A_for_b2 = (10 - L_for_b2)/10
print('>>> Accuracy  =',A_for_b2 )

>>> Accuracy  = 1.0
